export default {
  "location": {
    "name": "London",
    "region": "City of London, Greater London",
    "country": "United Kingdom",
    "lat": 51.52,
    "lon": -0.11,
    "tz_id": "Europe/London",
    "localtime_epoch": 1695548084,
    "localtime": "2023-09-24 10:34"
  },
  "current": {
    "last_updated_epoch": 1695547800,
    "last_updated": "2023-09-24 10:30",
    "temp_c": 18,
    "temp_f": 64.4,
    "is_day": 1,
    "condition": {
      "text": "Partly cloudy",
      "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
      "code": 1003
    },
    "wind_mph": 13.6,
    "wind_kph": 22,
    "wind_degree": 180,
    "wind_dir": "S",
    "pressure_mb": 1018,
    "pressure_in": 30.06,
    "precip_mm": 0,
    "precip_in": 0,
    "humidity": 77,
    "cloud": 25,
    "feelslike_c": 18,
    "feelslike_f": 64.4,
    "vis_km": 10,
    "vis_miles": 6,
    "uv": 4,
    "gust_mph": 16.6,
    "gust_kph": 26.7
  },
  "forecast": {
    "forecastday": [
      {
        "date": "2023-09-24",
        "date_epoch": 1695513600,
        "day": {
          "maxtemp_c": 19.9,
          "maxtemp_f": 67.9,
          "mintemp_c": 13.9,
          "mintemp_f": 57,
          "avgtemp_c": 17,
          "avgtemp_f": 62.6,
          "maxwind_mph": 15,
          "maxwind_kph": 24.1,
          "totalprecip_mm": 0.01,
          "totalprecip_in": 0,
          "totalsnow_cm": 0,
          "avgvis_km": 10,
          "avgvis_miles": 6,
          "avghumidity": 67,
          "daily_will_it_rain": 0,
          "daily_chance_of_rain": 0,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Cloudy",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
            "code": 1006
          },
          "uv": 4
        },
        "astro": {
          "sunrise": "06:49 AM",
          "sunset": "06:55 PM",
          "moonrise": "05:16 PM",
          "moonset": "No moonset",
          "moon_phase": "Waxing Gibbous",
          "moon_illumination": "63",
          "is_moon_up": 0,
          "is_sun_up": 0
        },
        "hour": [
          {
            "time_epoch": 1695510000,
            "time": "2023-09-24 00:00",
            "temp_c": 13.9,
            "temp_f": 57,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 8.9,
            "wind_kph": 14.4,
            "wind_degree": 188,
            "wind_dir": "S",
            "pressure_mb": 1019,
            "pressure_in": 30.1,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 64,
            "cloud": 22,
            "feelslike_c": 12.8,
            "feelslike_f": 55,
            "windchill_c": 12.8,
            "windchill_f": 55,
            "heatindex_c": 13.9,
            "heatindex_f": 57,
            "dewpoint_c": 7.2,
            "dewpoint_f": 44.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 14.2,
            "gust_kph": 22.9,
            "uv": 1
          },
          {
            "time_epoch": 1695513600,
            "time": "2023-09-24 01:00",
            "temp_c": 14.1,
            "temp_f": 57.3,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 9.6,
            "wind_kph": 15.5,
            "wind_degree": 188,
            "wind_dir": "S",
            "pressure_mb": 1019,
            "pressure_in": 30.09,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 63,
            "cloud": 41,
            "feelslike_c": 12.9,
            "feelslike_f": 55.2,
            "windchill_c": 12.9,
            "windchill_f": 55.2,
            "heatindex_c": 14.1,
            "heatindex_f": 57.3,
            "dewpoint_c": 7.2,
            "dewpoint_f": 45,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 15.5,
            "gust_kph": 24.9,
            "uv": 1
          },
          {
            "time_epoch": 1695517200,
            "time": "2023-09-24 02:00",
            "temp_c": 14.6,
            "temp_f": 58.3,
            "is_day": 0,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 10.7,
            "wind_kph": 17.3,
            "wind_degree": 193,
            "wind_dir": "SSW",
            "pressure_mb": 1019,
            "pressure_in": 30.08,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 67,
            "cloud": 100,
            "feelslike_c": 13.4,
            "feelslike_f": 56.1,
            "windchill_c": 13.4,
            "windchill_f": 56.1,
            "heatindex_c": 14.6,
            "heatindex_f": 58.3,
            "dewpoint_c": 8.5,
            "dewpoint_f": 47.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 16.7,
            "gust_kph": 26.9,
            "uv": 1
          },
          {
            "time_epoch": 1695520800,
            "time": "2023-09-24 03:00",
            "temp_c": 14.7,
            "temp_f": 58.5,
            "is_day": 0,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "code": 1006
            },
            "wind_mph": 11.2,
            "wind_kph": 18,
            "wind_degree": 194,
            "wind_dir": "SSW",
            "pressure_mb": 1018,
            "pressure_in": 30.07,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 73,
            "cloud": 76,
            "feelslike_c": 13.5,
            "feelslike_f": 56.2,
            "windchill_c": 13.5,
            "windchill_f": 56.2,
            "heatindex_c": 14.7,
            "heatindex_f": 58.5,
            "dewpoint_c": 10,
            "dewpoint_f": 50,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 17,
            "gust_kph": 27.4,
            "uv": 1
          },
          {
            "time_epoch": 1695524400,
            "time": "2023-09-24 04:00",
            "temp_c": 15,
            "temp_f": 59,
            "is_day": 0,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 12.5,
            "wind_kph": 20.2,
            "wind_degree": 194,
            "wind_dir": "SSW",
            "pressure_mb": 1018,
            "pressure_in": 30.07,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 70,
            "cloud": 89,
            "feelslike_c": 15,
            "feelslike_f": 59,
            "windchill_c": 15,
            "windchill_f": 59,
            "heatindex_c": 15,
            "heatindex_f": 59,
            "dewpoint_c": 9.6,
            "dewpoint_f": 49.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 18.8,
            "gust_kph": 30.2,
            "uv": 1
          },
          {
            "time_epoch": 1695528000,
            "time": "2023-09-24 05:00",
            "temp_c": 14.9,
            "temp_f": 58.8,
            "is_day": 0,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "code": 1006
            },
            "wind_mph": 12.1,
            "wind_kph": 19.4,
            "wind_degree": 190,
            "wind_dir": "S",
            "pressure_mb": 1018,
            "pressure_in": 30.07,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 74,
            "cloud": 68,
            "feelslike_c": 13.6,
            "feelslike_f": 56.4,
            "windchill_c": 13.6,
            "windchill_f": 56.4,
            "heatindex_c": 14.9,
            "heatindex_f": 58.8,
            "dewpoint_c": 10.3,
            "dewpoint_f": 50.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 18.4,
            "gust_kph": 29.7,
            "uv": 1
          },
          {
            "time_epoch": 1695531600,
            "time": "2023-09-24 06:00",
            "temp_c": 14.7,
            "temp_f": 58.5,
            "is_day": 0,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "code": 1006
            },
            "wind_mph": 11.4,
            "wind_kph": 18.4,
            "wind_degree": 193,
            "wind_dir": "SSW",
            "pressure_mb": 1019,
            "pressure_in": 30.08,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 78,
            "cloud": 70,
            "feelslike_c": 13.5,
            "feelslike_f": 56.3,
            "windchill_c": 13.5,
            "windchill_f": 56.3,
            "heatindex_c": 14.8,
            "heatindex_f": 58.6,
            "dewpoint_c": 11,
            "dewpoint_f": 51.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 17.8,
            "gust_kph": 28.6,
            "uv": 1
          },
          {
            "time_epoch": 1695535200,
            "time": "2023-09-24 07:00",
            "temp_c": 15.1,
            "temp_f": 59.2,
            "is_day": 1,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "code": 1006
            },
            "wind_mph": 12.1,
            "wind_kph": 19.4,
            "wind_degree": 193,
            "wind_dir": "SSW",
            "pressure_mb": 1019,
            "pressure_in": 30.09,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 80,
            "cloud": 71,
            "feelslike_c": 15.1,
            "feelslike_f": 59.2,
            "windchill_c": 15.1,
            "windchill_f": 59.2,
            "heatindex_c": 15.1,
            "heatindex_f": 59.2,
            "dewpoint_c": 11.7,
            "dewpoint_f": 53.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 17.7,
            "gust_kph": 28.5,
            "uv": 4
          },
          {
            "time_epoch": 1695538800,
            "time": "2023-09-24 08:00",
            "temp_c": 16.4,
            "temp_f": 61.5,
            "is_day": 1,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
              "code": 1009
            },
            "wind_mph": 12.1,
            "wind_kph": 19.4,
            "wind_degree": 195,
            "wind_dir": "SSW",
            "pressure_mb": 1019,
            "pressure_in": 30.09,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 77,
            "cloud": 100,
            "feelslike_c": 16.4,
            "feelslike_f": 61.5,
            "windchill_c": 16.4,
            "windchill_f": 61.5,
            "heatindex_c": 16.4,
            "heatindex_f": 61.5,
            "dewpoint_c": 12.4,
            "dewpoint_f": 54.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 15.8,
            "gust_kph": 25.5,
            "uv": 4
          },
          {
            "time_epoch": 1695542400,
            "time": "2023-09-24 09:00",
            "temp_c": 16.6,
            "temp_f": 61.9,
            "is_day": 1,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "code": 1006
            },
            "wind_mph": 12.1,
            "wind_kph": 19.4,
            "wind_degree": 192,
            "wind_dir": "SSW",
            "pressure_mb": 1019,
            "pressure_in": 30.09,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 78,
            "cloud": 84,
            "feelslike_c": 16.6,
            "feelslike_f": 61.9,
            "windchill_c": 16.6,
            "windchill_f": 61.9,
            "heatindex_c": 16.6,
            "heatindex_f": 61.9,
            "dewpoint_c": 12.7,
            "dewpoint_f": 54.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 16.6,
            "gust_kph": 26.6,
            "uv": 4
          },
          {
            "time_epoch": 1695546000,
            "time": "2023-09-24 10:00",
            "temp_c": 18,
            "temp_f": 64.4,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 13.6,
            "wind_kph": 22,
            "wind_degree": 180,
            "wind_dir": "S",
            "pressure_mb": 1018,
            "pressure_in": 30.06,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 77,
            "cloud": 25,
            "feelslike_c": 18.6,
            "feelslike_f": 65.4,
            "windchill_c": 18.6,
            "windchill_f": 65.4,
            "heatindex_c": 18.6,
            "heatindex_f": 65.4,
            "dewpoint_c": 13,
            "dewpoint_f": 55.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 16.6,
            "gust_kph": 26.7,
            "uv": 4
          },
          {
            "time_epoch": 1695549600,
            "time": "2023-09-24 11:00",
            "temp_c": 18.8,
            "temp_f": 65.9,
            "is_day": 1,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "code": 1006
            },
            "wind_mph": 13.6,
            "wind_kph": 22,
            "wind_degree": 196,
            "wind_dir": "SSW",
            "pressure_mb": 1019,
            "pressure_in": 30.08,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 69,
            "cloud": 85,
            "feelslike_c": 18.8,
            "feelslike_f": 65.9,
            "windchill_c": 18.8,
            "windchill_f": 65.9,
            "heatindex_c": 18.8,
            "heatindex_f": 65.9,
            "dewpoint_c": 13.1,
            "dewpoint_f": 55.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 16.2,
            "gust_kph": 26.1,
            "uv": 4
          },
          {
            "time_epoch": 1695553200,
            "time": "2023-09-24 12:00",
            "temp_c": 18.2,
            "temp_f": 64.7,
            "is_day": 1,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
              "code": 1009
            },
            "wind_mph": 12.5,
            "wind_kph": 20.2,
            "wind_degree": 190,
            "wind_dir": "S",
            "pressure_mb": 1018,
            "pressure_in": 30.07,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 72,
            "cloud": 95,
            "feelslike_c": 18.2,
            "feelslike_f": 64.7,
            "windchill_c": 18.2,
            "windchill_f": 64.7,
            "heatindex_c": 18.2,
            "heatindex_f": 64.7,
            "dewpoint_c": 13.1,
            "dewpoint_f": 55.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 16,
            "gust_kph": 25.8,
            "uv": 4
          },
          {
            "time_epoch": 1695556800,
            "time": "2023-09-24 13:00",
            "temp_c": 18.6,
            "temp_f": 65.4,
            "is_day": 1,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
              "code": 1009
            },
            "wind_mph": 13,
            "wind_kph": 20.9,
            "wind_degree": 190,
            "wind_dir": "S",
            "pressure_mb": 1018,
            "pressure_in": 30.06,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 70,
            "cloud": 92,
            "feelslike_c": 18.6,
            "feelslike_f": 65.4,
            "windchill_c": 18.6,
            "windchill_f": 65.4,
            "heatindex_c": 18.6,
            "heatindex_f": 65.4,
            "dewpoint_c": 12.9,
            "dewpoint_f": 55.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 16.8,
            "gust_kph": 27,
            "uv": 4
          },
          {
            "time_epoch": 1695560400,
            "time": "2023-09-24 14:00",
            "temp_c": 19.9,
            "temp_f": 67.9,
            "is_day": 1,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
              "code": 1009
            },
            "wind_mph": 15,
            "wind_kph": 24.1,
            "wind_degree": 192,
            "wind_dir": "SSW",
            "pressure_mb": 1017,
            "pressure_in": 30.04,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 62,
            "cloud": 100,
            "feelslike_c": 19.9,
            "feelslike_f": 67.9,
            "windchill_c": 19.9,
            "windchill_f": 67.9,
            "heatindex_c": 19.9,
            "heatindex_f": 67.9,
            "dewpoint_c": 12.6,
            "dewpoint_f": 54.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 17.2,
            "gust_kph": 27.8,
            "uv": 4
          },
          {
            "time_epoch": 1695564000,
            "time": "2023-09-24 15:00",
            "temp_c": 19.7,
            "temp_f": 67.5,
            "is_day": 1,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "code": 1006
            },
            "wind_mph": 14.5,
            "wind_kph": 23.4,
            "wind_degree": 190,
            "wind_dir": "S",
            "pressure_mb": 1017,
            "pressure_in": 30.03,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 62,
            "cloud": 73,
            "feelslike_c": 19.7,
            "feelslike_f": 67.5,
            "windchill_c": 19.7,
            "windchill_f": 67.5,
            "heatindex_c": 19.7,
            "heatindex_f": 67.5,
            "dewpoint_c": 12.3,
            "dewpoint_f": 54.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 16.8,
            "gust_kph": 27,
            "uv": 4
          },
          {
            "time_epoch": 1695567600,
            "time": "2023-09-24 16:00",
            "temp_c": 19.3,
            "temp_f": 66.7,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 14.1,
            "wind_kph": 22.7,
            "wind_degree": 187,
            "wind_dir": "S",
            "pressure_mb": 1017,
            "pressure_in": 30.02,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 61,
            "cloud": 28,
            "feelslike_c": 19.3,
            "feelslike_f": 66.8,
            "windchill_c": 19.3,
            "windchill_f": 66.8,
            "heatindex_c": 19.3,
            "heatindex_f": 66.8,
            "dewpoint_c": 11.7,
            "dewpoint_f": 53,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 17.1,
            "gust_kph": 27.5,
            "uv": 5
          },
          {
            "time_epoch": 1695571200,
            "time": "2023-09-24 17:00",
            "temp_c": 18.5,
            "temp_f": 65.2,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 13.4,
            "wind_kph": 21.6,
            "wind_degree": 181,
            "wind_dir": "S",
            "pressure_mb": 1016,
            "pressure_in": 30.02,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 60,
            "cloud": 30,
            "feelslike_c": 18.5,
            "feelslike_f": 65.2,
            "windchill_c": 18.5,
            "windchill_f": 65.2,
            "heatindex_c": 18.5,
            "heatindex_f": 65.2,
            "dewpoint_c": 10.7,
            "dewpoint_f": 51.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 18.3,
            "gust_kph": 29.5,
            "uv": 5
          },
          {
            "time_epoch": 1695574800,
            "time": "2023-09-24 18:00",
            "temp_c": 17.7,
            "temp_f": 63.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 13.2,
            "wind_kph": 21.2,
            "wind_degree": 178,
            "wind_dir": "S",
            "pressure_mb": 1016,
            "pressure_in": 30.02,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 57,
            "cloud": 19,
            "feelslike_c": 17.7,
            "feelslike_f": 63.9,
            "windchill_c": 17.7,
            "windchill_f": 63.9,
            "heatindex_c": 17.7,
            "heatindex_f": 63.9,
            "dewpoint_c": 9.3,
            "dewpoint_f": 48.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 20,
            "gust_kph": 32.2,
            "uv": 5
          },
          {
            "time_epoch": 1695578400,
            "time": "2023-09-24 19:00",
            "temp_c": 17.8,
            "temp_f": 64.1,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 13.4,
            "wind_kph": 21.6,
            "wind_degree": 179,
            "wind_dir": "S",
            "pressure_mb": 1016,
            "pressure_in": 30.01,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 56,
            "cloud": 9,
            "feelslike_c": 17.8,
            "feelslike_f": 64.1,
            "windchill_c": 17.8,
            "windchill_f": 64.1,
            "heatindex_c": 17.8,
            "heatindex_f": 64.1,
            "dewpoint_c": 9,
            "dewpoint_f": 48.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 20.6,
            "gust_kph": 33.2,
            "uv": 1
          },
          {
            "time_epoch": 1695582000,
            "time": "2023-09-24 20:00",
            "temp_c": 17.9,
            "temp_f": 64.2,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 14.1,
            "wind_kph": 22.7,
            "wind_degree": 178,
            "wind_dir": "S",
            "pressure_mb": 1016,
            "pressure_in": 30,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 59,
            "cloud": 3,
            "feelslike_c": 17.9,
            "feelslike_f": 64.2,
            "windchill_c": 17.9,
            "windchill_f": 64.2,
            "heatindex_c": 17.9,
            "heatindex_f": 64.2,
            "dewpoint_c": 9.8,
            "dewpoint_f": 49.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 22,
            "gust_kph": 35.4,
            "uv": 1
          },
          {
            "time_epoch": 1695585600,
            "time": "2023-09-24 21:00",
            "temp_c": 17.9,
            "temp_f": 64.2,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 14.5,
            "wind_kph": 23.4,
            "wind_degree": 182,
            "wind_dir": "S",
            "pressure_mb": 1016,
            "pressure_in": 29.99,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 60,
            "cloud": 6,
            "feelslike_c": 17.9,
            "feelslike_f": 64.1,
            "windchill_c": 17.9,
            "windchill_f": 64.1,
            "heatindex_c": 17.9,
            "heatindex_f": 64.1,
            "dewpoint_c": 10.1,
            "dewpoint_f": 50.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 22.8,
            "gust_kph": 36.8,
            "uv": 1
          },
          {
            "time_epoch": 1695589200,
            "time": "2023-09-24 22:00",
            "temp_c": 17.6,
            "temp_f": 63.7,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 14.8,
            "wind_kph": 23.8,
            "wind_degree": 187,
            "wind_dir": "S",
            "pressure_mb": 1016,
            "pressure_in": 29.99,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 60,
            "cloud": 25,
            "feelslike_c": 17.6,
            "feelslike_f": 63.7,
            "windchill_c": 17.6,
            "windchill_f": 63.7,
            "heatindex_c": 17.6,
            "heatindex_f": 63.7,
            "dewpoint_c": 9.7,
            "dewpoint_f": 49.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 23.5,
            "gust_kph": 37.8,
            "uv": 1
          },
          {
            "time_epoch": 1695592800,
            "time": "2023-09-24 23:00",
            "temp_c": 17.5,
            "temp_f": 63.4,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 13.9,
            "wind_kph": 22.3,
            "wind_degree": 197,
            "wind_dir": "SSW",
            "pressure_mb": 1016,
            "pressure_in": 29.99,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 62,
            "cloud": 23,
            "feelslike_c": 17.5,
            "feelslike_f": 63.4,
            "windchill_c": 17.5,
            "windchill_f": 63.4,
            "heatindex_c": 17.5,
            "heatindex_f": 63.4,
            "dewpoint_c": 10.1,
            "dewpoint_f": 50.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 21.9,
            "gust_kph": 35.2,
            "uv": 1
          }
        ]
      },
      {
        "date": "2023-09-25",
        "date_epoch": 1695600000,
        "day": {
          "maxtemp_c": 22,
          "maxtemp_f": 71.6,
          "mintemp_c": 15.3,
          "mintemp_f": 59.6,
          "avgtemp_c": 18.1,
          "avgtemp_f": 64.7,
          "maxwind_mph": 13,
          "maxwind_kph": 20.9,
          "totalprecip_mm": 0.07,
          "totalprecip_in": 0,
          "totalsnow_cm": 0,
          "avgvis_km": 10,
          "avgvis_miles": 6,
          "avghumidity": 65,
          "daily_will_it_rain": 0,
          "daily_chance_of_rain": 0,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Partly cloudy",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
            "code": 1003
          },
          "uv": 5
        },
        "astro": {
          "sunrise": "06:51 AM",
          "sunset": "06:53 PM",
          "moonrise": "05:48 PM",
          "moonset": "12:33 AM",
          "moon_phase": "Waxing Gibbous",
          "moon_illumination": "74",
          "is_moon_up": 0,
          "is_sun_up": 0
        },
        "hour": [
          {
            "time_epoch": 1695596400,
            "time": "2023-09-25 00:00",
            "temp_c": 17.2,
            "temp_f": 63,
            "is_day": 0,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 13,
            "wind_kph": 20.9,
            "wind_degree": 200,
            "wind_dir": "SSW",
            "pressure_mb": 1015,
            "pressure_in": 29.99,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 67,
            "cloud": 100,
            "feelslike_c": 17.2,
            "feelslike_f": 63,
            "windchill_c": 17.2,
            "windchill_f": 63,
            "heatindex_c": 17.2,
            "heatindex_f": 63,
            "dewpoint_c": 11,
            "dewpoint_f": 51.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 19.8,
            "gust_kph": 31.9,
            "uv": 1
          },
          {
            "time_epoch": 1695600000,
            "time": "2023-09-25 01:00",
            "temp_c": 17,
            "temp_f": 62.6,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 11.9,
            "wind_kph": 19.1,
            "wind_degree": 203,
            "wind_dir": "SSW",
            "pressure_mb": 1016,
            "pressure_in": 29.99,
            "precip_mm": 0.02,
            "precip_in": 0,
            "humidity": 76,
            "cloud": 100,
            "feelslike_c": 17,
            "feelslike_f": 62.6,
            "windchill_c": 17,
            "windchill_f": 62.6,
            "heatindex_c": 17,
            "heatindex_f": 62.6,
            "dewpoint_c": 12.7,
            "dewpoint_f": 54.8,
            "will_it_rain": 1,
            "chance_of_rain": 75,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 17.2,
            "gust_kph": 27.7,
            "uv": 1
          },
          {
            "time_epoch": 1695603600,
            "time": "2023-09-25 02:00",
            "temp_c": 16.9,
            "temp_f": 62.5,
            "is_day": 0,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 10.5,
            "wind_kph": 16.9,
            "wind_degree": 206,
            "wind_dir": "SSW",
            "pressure_mb": 1016,
            "pressure_in": 29.99,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 82,
            "cloud": 100,
            "feelslike_c": 16.9,
            "feelslike_f": 62.5,
            "windchill_c": 16.9,
            "windchill_f": 62.5,
            "heatindex_c": 16.9,
            "heatindex_f": 62.5,
            "dewpoint_c": 13.8,
            "dewpoint_f": 56.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 15.2,
            "gust_kph": 24.5,
            "uv": 1
          },
          {
            "time_epoch": 1695607200,
            "time": "2023-09-25 03:00",
            "temp_c": 17,
            "temp_f": 62.6,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 9.2,
            "wind_kph": 14.8,
            "wind_degree": 212,
            "wind_dir": "SSW",
            "pressure_mb": 1016,
            "pressure_in": 29.99,
            "precip_mm": 0.02,
            "precip_in": 0,
            "humidity": 86,
            "cloud": 100,
            "feelslike_c": 17,
            "feelslike_f": 62.6,
            "windchill_c": 17,
            "windchill_f": 62.6,
            "heatindex_c": 17,
            "heatindex_f": 62.6,
            "dewpoint_c": 14.6,
            "dewpoint_f": 58.4,
            "will_it_rain": 1,
            "chance_of_rain": 72,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.5,
            "gust_kph": 21.7,
            "uv": 1
          },
          {
            "time_epoch": 1695610800,
            "time": "2023-09-25 04:00",
            "temp_c": 17.1,
            "temp_f": 62.8,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 8.1,
            "wind_kph": 13,
            "wind_degree": 229,
            "wind_dir": "SW",
            "pressure_mb": 1016,
            "pressure_in": 30.01,
            "precip_mm": 0.03,
            "precip_in": 0,
            "humidity": 86,
            "cloud": 79,
            "feelslike_c": 17.1,
            "feelslike_f": 62.7,
            "windchill_c": 17.1,
            "windchill_f": 62.7,
            "heatindex_c": 17.1,
            "heatindex_f": 62.7,
            "dewpoint_c": 14.8,
            "dewpoint_f": 58.6,
            "will_it_rain": 0,
            "chance_of_rain": 60,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12,
            "gust_kph": 19.4,
            "uv": 1
          },
          {
            "time_epoch": 1695614400,
            "time": "2023-09-25 05:00",
            "temp_c": 16.5,
            "temp_f": 61.7,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 7.4,
            "wind_kph": 11.9,
            "wind_degree": 234,
            "wind_dir": "SW",
            "pressure_mb": 1017,
            "pressure_in": 30.03,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 84,
            "cloud": 7,
            "feelslike_c": 16.5,
            "feelslike_f": 61.7,
            "windchill_c": 16.5,
            "windchill_f": 61.7,
            "heatindex_c": 16.5,
            "heatindex_f": 61.7,
            "dewpoint_c": 13.8,
            "dewpoint_f": 56.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.2,
            "gust_kph": 18,
            "uv": 1
          },
          {
            "time_epoch": 1695618000,
            "time": "2023-09-25 06:00",
            "temp_c": 15.3,
            "temp_f": 59.6,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 6.3,
            "wind_kph": 10.1,
            "wind_degree": 222,
            "wind_dir": "SW",
            "pressure_mb": 1018,
            "pressure_in": 30.05,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 88,
            "cloud": 14,
            "feelslike_c": 15.3,
            "feelslike_f": 59.6,
            "windchill_c": 15.3,
            "windchill_f": 59.6,
            "heatindex_c": 15.3,
            "heatindex_f": 59.6,
            "dewpoint_c": 13.3,
            "dewpoint_f": 55.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.9,
            "gust_kph": 15.9,
            "uv": 1
          },
          {
            "time_epoch": 1695621600,
            "time": "2023-09-25 07:00",
            "temp_c": 15.5,
            "temp_f": 60,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 6.5,
            "wind_kph": 10.4,
            "wind_degree": 224,
            "wind_dir": "SW",
            "pressure_mb": 1018,
            "pressure_in": 30.07,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 84,
            "cloud": 11,
            "feelslike_c": 15.5,
            "feelslike_f": 60,
            "windchill_c": 15.5,
            "windchill_f": 60,
            "heatindex_c": 15.5,
            "heatindex_f": 60,
            "dewpoint_c": 12.9,
            "dewpoint_f": 55.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.3,
            "gust_kph": 14.9,
            "uv": 5
          },
          {
            "time_epoch": 1695625200,
            "time": "2023-09-25 08:00",
            "temp_c": 16.7,
            "temp_f": 62,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.1,
            "wind_kph": 13,
            "wind_degree": 230,
            "wind_dir": "SW",
            "pressure_mb": 1019,
            "pressure_in": 30.09,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 74,
            "cloud": 0,
            "feelslike_c": 16.7,
            "feelslike_f": 62,
            "windchill_c": 16.7,
            "windchill_f": 62,
            "heatindex_c": 16.7,
            "heatindex_f": 62,
            "dewpoint_c": 12,
            "dewpoint_f": 53.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.3,
            "gust_kph": 16.6,
            "uv": 5
          },
          {
            "time_epoch": 1695628800,
            "time": "2023-09-25 09:00",
            "temp_c": 18,
            "temp_f": 64.4,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.7,
            "wind_kph": 14,
            "wind_degree": 235,
            "wind_dir": "SW",
            "pressure_mb": 1019,
            "pressure_in": 30.1,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 65,
            "cloud": 4,
            "feelslike_c": 18,
            "feelslike_f": 64.4,
            "windchill_c": 18,
            "windchill_f": 64.4,
            "heatindex_c": 18,
            "heatindex_f": 64.4,
            "dewpoint_c": 11.3,
            "dewpoint_f": 52.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.2,
            "gust_kph": 16.5,
            "uv": 5
          },
          {
            "time_epoch": 1695632400,
            "time": "2023-09-25 10:00",
            "temp_c": 19.2,
            "temp_f": 66.5,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.9,
            "wind_kph": 14.4,
            "wind_degree": 236,
            "wind_dir": "WSW",
            "pressure_mb": 1019,
            "pressure_in": 30.1,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 58,
            "cloud": 9,
            "feelslike_c": 19.2,
            "feelslike_f": 66.5,
            "windchill_c": 19.2,
            "windchill_f": 66.5,
            "heatindex_c": 19.2,
            "heatindex_f": 66.5,
            "dewpoint_c": 10.8,
            "dewpoint_f": 51.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.3,
            "gust_kph": 16.6,
            "uv": 5
          },
          {
            "time_epoch": 1695636000,
            "time": "2023-09-25 11:00",
            "temp_c": 20.1,
            "temp_f": 68.2,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.9,
            "wind_kph": 14.4,
            "wind_degree": 233,
            "wind_dir": "SW",
            "pressure_mb": 1019,
            "pressure_in": 30.1,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 52,
            "cloud": 15,
            "feelslike_c": 20.1,
            "feelslike_f": 68.2,
            "windchill_c": 20.1,
            "windchill_f": 68.2,
            "heatindex_c": 20.1,
            "heatindex_f": 68.2,
            "dewpoint_c": 10.1,
            "dewpoint_f": 50.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.3,
            "gust_kph": 16.6,
            "uv": 6
          },
          {
            "time_epoch": 1695639600,
            "time": "2023-09-25 12:00",
            "temp_c": 21,
            "temp_f": 69.8,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.9,
            "wind_kph": 14.4,
            "wind_degree": 234,
            "wind_dir": "SW",
            "pressure_mb": 1019,
            "pressure_in": 30.1,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 47,
            "cloud": 0,
            "feelslike_c": 21,
            "feelslike_f": 69.8,
            "windchill_c": 21,
            "windchill_f": 69.8,
            "heatindex_c": 24.2,
            "heatindex_f": 75.5,
            "dewpoint_c": 9.4,
            "dewpoint_f": 48.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.3,
            "gust_kph": 16.6,
            "uv": 6
          },
          {
            "time_epoch": 1695643200,
            "time": "2023-09-25 13:00",
            "temp_c": 21.8,
            "temp_f": 71.3,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.9,
            "wind_kph": 14.4,
            "wind_degree": 235,
            "wind_dir": "SW",
            "pressure_mb": 1019,
            "pressure_in": 30.09,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 43,
            "cloud": 10,
            "feelslike_c": 21.8,
            "feelslike_f": 71.3,
            "windchill_c": 21.8,
            "windchill_f": 71.3,
            "heatindex_c": 24.1,
            "heatindex_f": 75.4,
            "dewpoint_c": 8.7,
            "dewpoint_f": 47.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.3,
            "gust_kph": 16.6,
            "uv": 6
          },
          {
            "time_epoch": 1695646800,
            "time": "2023-09-25 14:00",
            "temp_c": 22,
            "temp_f": 71.6,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.9,
            "wind_kph": 14.4,
            "wind_degree": 232,
            "wind_dir": "SW",
            "pressure_mb": 1019,
            "pressure_in": 30.09,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 41,
            "cloud": 10,
            "feelslike_c": 24.1,
            "feelslike_f": 75.3,
            "windchill_c": 22,
            "windchill_f": 71.6,
            "heatindex_c": 24.1,
            "heatindex_f": 75.3,
            "dewpoint_c": 8.2,
            "dewpoint_f": 46.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.3,
            "gust_kph": 16.6,
            "uv": 6
          },
          {
            "time_epoch": 1695650400,
            "time": "2023-09-25 15:00",
            "temp_c": 21.8,
            "temp_f": 71.3,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 9.2,
            "wind_kph": 14.8,
            "wind_degree": 226,
            "wind_dir": "SW",
            "pressure_mb": 1019,
            "pressure_in": 30.08,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 41,
            "cloud": 14,
            "feelslike_c": 21.8,
            "feelslike_f": 71.3,
            "windchill_c": 21.8,
            "windchill_f": 71.3,
            "heatindex_c": 24,
            "heatindex_f": 75.2,
            "dewpoint_c": 7.9,
            "dewpoint_f": 46.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.8,
            "gust_kph": 17.4,
            "uv": 6
          },
          {
            "time_epoch": 1695654000,
            "time": "2023-09-25 16:00",
            "temp_c": 21.1,
            "temp_f": 70,
            "is_day": 1,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
              "code": 1009
            },
            "wind_mph": 8.9,
            "wind_kph": 14.4,
            "wind_degree": 217,
            "wind_dir": "SW",
            "pressure_mb": 1019,
            "pressure_in": 30.09,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 43,
            "cloud": 97,
            "feelslike_c": 21.1,
            "feelslike_f": 70,
            "windchill_c": 21.1,
            "windchill_f": 70,
            "heatindex_c": 24,
            "heatindex_f": 75.2,
            "dewpoint_c": 8.1,
            "dewpoint_f": 46.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.5,
            "gust_kph": 18.5,
            "uv": 5
          },
          {
            "time_epoch": 1695657600,
            "time": "2023-09-25 17:00",
            "temp_c": 19.9,
            "temp_f": 67.7,
            "is_day": 1,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
              "code": 1009
            },
            "wind_mph": 8.5,
            "wind_kph": 13.7,
            "wind_degree": 207,
            "wind_dir": "SSW",
            "pressure_mb": 1019,
            "pressure_in": 30.1,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 50,
            "cloud": 100,
            "feelslike_c": 19.9,
            "feelslike_f": 67.7,
            "windchill_c": 19.9,
            "windchill_f": 67.7,
            "heatindex_c": 19.9,
            "heatindex_f": 67.7,
            "dewpoint_c": 9.1,
            "dewpoint_f": 48.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.7,
            "gust_kph": 18.8,
            "uv": 4
          },
          {
            "time_epoch": 1695661200,
            "time": "2023-09-25 18:00",
            "temp_c": 18.4,
            "temp_f": 65.1,
            "is_day": 1,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
              "code": 1009
            },
            "wind_mph": 8.1,
            "wind_kph": 13,
            "wind_degree": 204,
            "wind_dir": "SSW",
            "pressure_mb": 1020,
            "pressure_in": 30.11,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 57,
            "cloud": 100,
            "feelslike_c": 18.4,
            "feelslike_f": 65.1,
            "windchill_c": 18.4,
            "windchill_f": 65.1,
            "heatindex_c": 18.4,
            "heatindex_f": 65.1,
            "dewpoint_c": 9.8,
            "dewpoint_f": 49.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.5,
            "gust_kph": 18.6,
            "uv": 4
          },
          {
            "time_epoch": 1695664800,
            "time": "2023-09-25 19:00",
            "temp_c": 17.7,
            "temp_f": 63.8,
            "is_day": 0,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 6.7,
            "wind_kph": 10.8,
            "wind_degree": 204,
            "wind_dir": "SSW",
            "pressure_mb": 1020,
            "pressure_in": 30.12,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 61,
            "cloud": 100,
            "feelslike_c": 17.7,
            "feelslike_f": 63.8,
            "windchill_c": 17.7,
            "windchill_f": 63.8,
            "heatindex_c": 17.7,
            "heatindex_f": 63.8,
            "dewpoint_c": 10.2,
            "dewpoint_f": 50.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.5,
            "gust_kph": 15.3,
            "uv": 1
          },
          {
            "time_epoch": 1695668400,
            "time": "2023-09-25 20:00",
            "temp_c": 17,
            "temp_f": 62.6,
            "is_day": 0,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 6.3,
            "wind_kph": 10.1,
            "wind_degree": 206,
            "wind_dir": "SSW",
            "pressure_mb": 1020,
            "pressure_in": 30.12,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 65,
            "cloud": 100,
            "feelslike_c": 17,
            "feelslike_f": 62.6,
            "windchill_c": 17,
            "windchill_f": 62.6,
            "heatindex_c": 17,
            "heatindex_f": 62.6,
            "dewpoint_c": 10.5,
            "dewpoint_f": 50.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9,
            "gust_kph": 14.5,
            "uv": 1
          },
          {
            "time_epoch": 1695672000,
            "time": "2023-09-25 21:00",
            "temp_c": 16.5,
            "temp_f": 61.7,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 5.1,
            "wind_kph": 8.3,
            "wind_degree": 203,
            "wind_dir": "SSW",
            "pressure_mb": 1020,
            "pressure_in": 30.11,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 68,
            "cloud": 6,
            "feelslike_c": 16.5,
            "feelslike_f": 61.7,
            "windchill_c": 16.5,
            "windchill_f": 61.7,
            "heatindex_c": 16.5,
            "heatindex_f": 61.7,
            "dewpoint_c": 10.7,
            "dewpoint_f": 51.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.5,
            "gust_kph": 12.1,
            "uv": 1
          },
          {
            "time_epoch": 1695675600,
            "time": "2023-09-25 22:00",
            "temp_c": 16.2,
            "temp_f": 61.1,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 4.3,
            "wind_kph": 6.8,
            "wind_degree": 188,
            "wind_dir": "S",
            "pressure_mb": 1019,
            "pressure_in": 30.1,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 71,
            "cloud": 53,
            "feelslike_c": 16.2,
            "feelslike_f": 61.1,
            "windchill_c": 16.2,
            "windchill_f": 61.1,
            "heatindex_c": 16.2,
            "heatindex_f": 61.1,
            "dewpoint_c": 10.9,
            "dewpoint_f": 51.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.2,
            "gust_kph": 10,
            "uv": 1
          },
          {
            "time_epoch": 1695679200,
            "time": "2023-09-25 23:00",
            "temp_c": 15.6,
            "temp_f": 60,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4.3,
            "wind_kph": 6.8,
            "wind_degree": 176,
            "wind_dir": "S",
            "pressure_mb": 1019,
            "pressure_in": 30.09,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 74,
            "cloud": 22,
            "feelslike_c": 15.6,
            "feelslike_f": 60,
            "windchill_c": 15.6,
            "windchill_f": 60,
            "heatindex_c": 15.6,
            "heatindex_f": 60,
            "dewpoint_c": 11,
            "dewpoint_f": 51.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.5,
            "gust_kph": 10.5,
            "uv": 1
          }
        ]
      },
      {
        "date": "2023-09-26",
        "date_epoch": 1695686400,
        "day": {
          "maxtemp_c": 21.6,
          "maxtemp_f": 70.9,
          "mintemp_c": 14.4,
          "mintemp_f": 58,
          "avgtemp_c": 17.3,
          "avgtemp_f": 63.1,
          "maxwind_mph": 12.5,
          "maxwind_kph": 20.2,
          "totalprecip_mm": 0.61,
          "totalprecip_in": 0.02,
          "totalsnow_cm": 0,
          "avgvis_km": 9.8,
          "avgvis_miles": 6,
          "avghumidity": 75,
          "daily_will_it_rain": 1,
          "daily_chance_of_rain": 87,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Patchy rain possible",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
            "code": 1063
          },
          "uv": 4
        },
        "astro": {
          "sunrise": "06:52 AM",
          "sunset": "06:50 PM",
          "moonrise": "06:10 PM",
          "moonset": "02:05 AM",
          "moon_phase": "Waxing Gibbous",
          "moon_illumination": "84",
          "is_moon_up": 1,
          "is_sun_up": 0
        },
        "hour": [
          {
            "time_epoch": 1695682800,
            "time": "2023-09-26 00:00",
            "temp_c": 15.2,
            "temp_f": 59.4,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4.3,
            "wind_kph": 6.8,
            "wind_degree": 187,
            "wind_dir": "S",
            "pressure_mb": 1019,
            "pressure_in": 30.08,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 77,
            "cloud": 7,
            "feelslike_c": 15.2,
            "feelslike_f": 59.4,
            "windchill_c": 15.2,
            "windchill_f": 59.4,
            "heatindex_c": 15.2,
            "heatindex_f": 59.4,
            "dewpoint_c": 11.2,
            "dewpoint_f": 52.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.6,
            "gust_kph": 10.7,
            "uv": 1
          },
          {
            "time_epoch": 1695686400,
            "time": "2023-09-26 01:00",
            "temp_c": 14.8,
            "temp_f": 58.6,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4,
            "wind_kph": 6.5,
            "wind_degree": 173,
            "wind_dir": "S",
            "pressure_mb": 1018,
            "pressure_in": 30.07,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 80,
            "cloud": 6,
            "feelslike_c": 14.9,
            "feelslike_f": 58.8,
            "windchill_c": 14.9,
            "windchill_f": 58.8,
            "heatindex_c": 14.8,
            "heatindex_f": 58.6,
            "dewpoint_c": 11.3,
            "dewpoint_f": 52.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.7,
            "gust_kph": 10.7,
            "uv": 1
          },
          {
            "time_epoch": 1695690000,
            "time": "2023-09-26 02:00",
            "temp_c": 14.6,
            "temp_f": 58.3,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.8,
            "wind_kph": 6.1,
            "wind_degree": 160,
            "wind_dir": "SSE",
            "pressure_mb": 1018,
            "pressure_in": 30.05,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 81,
            "cloud": 6,
            "feelslike_c": 14.7,
            "feelslike_f": 58.5,
            "windchill_c": 14.7,
            "windchill_f": 58.5,
            "heatindex_c": 14.6,
            "heatindex_f": 58.3,
            "dewpoint_c": 11.4,
            "dewpoint_f": 52.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.5,
            "gust_kph": 10.5,
            "uv": 1
          },
          {
            "time_epoch": 1695693600,
            "time": "2023-09-26 03:00",
            "temp_c": 14.4,
            "temp_f": 58,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.8,
            "wind_kph": 6.1,
            "wind_degree": 149,
            "wind_dir": "SSE",
            "pressure_mb": 1017,
            "pressure_in": 30.03,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 82,
            "cloud": 9,
            "feelslike_c": 14.6,
            "feelslike_f": 58.2,
            "windchill_c": 14.6,
            "windchill_f": 58.2,
            "heatindex_c": 14.4,
            "heatindex_f": 58,
            "dewpoint_c": 11.4,
            "dewpoint_f": 52.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.8,
            "gust_kph": 10.9,
            "uv": 1
          },
          {
            "time_epoch": 1695697200,
            "time": "2023-09-26 04:00",
            "temp_c": 14.5,
            "temp_f": 58.1,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 4,
            "wind_kph": 6.5,
            "wind_degree": 152,
            "wind_dir": "SSE",
            "pressure_mb": 1016,
            "pressure_in": 30.01,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 81,
            "cloud": 26,
            "feelslike_c": 14.6,
            "feelslike_f": 58.2,
            "windchill_c": 14.6,
            "windchill_f": 58.2,
            "heatindex_c": 14.5,
            "heatindex_f": 58.1,
            "dewpoint_c": 11.3,
            "dewpoint_f": 52.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.2,
            "gust_kph": 11.6,
            "uv": 1
          },
          {
            "time_epoch": 1695700800,
            "time": "2023-09-26 05:00",
            "temp_c": 14.5,
            "temp_f": 58.2,
            "is_day": 0,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "code": 1006
            },
            "wind_mph": 4,
            "wind_kph": 6.5,
            "wind_degree": 174,
            "wind_dir": "S",
            "pressure_mb": 1016,
            "pressure_in": 30.01,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 83,
            "cloud": 79,
            "feelslike_c": 14.6,
            "feelslike_f": 58.2,
            "windchill_c": 14.6,
            "windchill_f": 58.2,
            "heatindex_c": 14.5,
            "heatindex_f": 58.2,
            "dewpoint_c": 11.7,
            "dewpoint_f": 53.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.1,
            "gust_kph": 11.4,
            "uv": 1
          },
          {
            "time_epoch": 1695704400,
            "time": "2023-09-26 06:00",
            "temp_c": 15.2,
            "temp_f": 59.4,
            "is_day": 0,
            "condition": {
              "text": "Thundery outbreaks possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/200.png",
              "code": 1087
            },
            "wind_mph": 4.7,
            "wind_kph": 7.6,
            "wind_degree": 166,
            "wind_dir": "SSE",
            "pressure_mb": 1016,
            "pressure_in": 29.99,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 86,
            "cloud": 40,
            "feelslike_c": 15.2,
            "feelslike_f": 59.4,
            "windchill_c": 15.2,
            "windchill_f": 59.4,
            "heatindex_c": 15.2,
            "heatindex_f": 59.4,
            "dewpoint_c": 12.8,
            "dewpoint_f": 55.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9,
            "vis_miles": 5,
            "gust_mph": 7.9,
            "gust_kph": 12.6,
            "uv": 1
          },
          {
            "time_epoch": 1695708000,
            "time": "2023-09-26 07:00",
            "temp_c": 15.7,
            "temp_f": 60.2,
            "is_day": 1,
            "condition": {
              "text": "Thundery outbreaks possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/200.png",
              "code": 1087
            },
            "wind_mph": 5.4,
            "wind_kph": 8.6,
            "wind_degree": 182,
            "wind_dir": "S",
            "pressure_mb": 1015,
            "pressure_in": 29.98,
            "precip_mm": 0.01,
            "precip_in": 0,
            "humidity": 89,
            "cloud": 69,
            "feelslike_c": 15.7,
            "feelslike_f": 60.2,
            "windchill_c": 15.7,
            "windchill_f": 60.2,
            "heatindex_c": 15.7,
            "heatindex_f": 60.2,
            "dewpoint_c": 13.9,
            "dewpoint_f": 57.1,
            "will_it_rain": 1,
            "chance_of_rain": 82,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9,
            "vis_miles": 5,
            "gust_mph": 8.8,
            "gust_kph": 14.1,
            "uv": 4
          },
          {
            "time_epoch": 1695711600,
            "time": "2023-09-26 08:00",
            "temp_c": 17.1,
            "temp_f": 62.8,
            "is_day": 1,
            "condition": {
              "text": "Thundery outbreaks possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/200.png",
              "code": 1087
            },
            "wind_mph": 7.4,
            "wind_kph": 11.9,
            "wind_degree": 199,
            "wind_dir": "SSW",
            "pressure_mb": 1015,
            "pressure_in": 29.98,
            "precip_mm": 0.08,
            "precip_in": 0,
            "humidity": 86,
            "cloud": 96,
            "feelslike_c": 17.1,
            "feelslike_f": 62.8,
            "windchill_c": 17.1,
            "windchill_f": 62.8,
            "heatindex_c": 17.1,
            "heatindex_f": 62.8,
            "dewpoint_c": 14.8,
            "dewpoint_f": 58.6,
            "will_it_rain": 1,
            "chance_of_rain": 74,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9,
            "vis_miles": 5,
            "gust_mph": 10,
            "gust_kph": 16.1,
            "uv": 4
          },
          {
            "time_epoch": 1695715200,
            "time": "2023-09-26 09:00",
            "temp_c": 18.1,
            "temp_f": 64.7,
            "is_day": 1,
            "condition": {
              "text": "Light rain shower",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
              "code": 1240
            },
            "wind_mph": 9.4,
            "wind_kph": 15.1,
            "wind_degree": 205,
            "wind_dir": "SSW",
            "pressure_mb": 1015,
            "pressure_in": 29.98,
            "precip_mm": 0.17,
            "precip_in": 0.01,
            "humidity": 76,
            "cloud": 80,
            "feelslike_c": 18.1,
            "feelslike_f": 64.7,
            "windchill_c": 18.1,
            "windchill_f": 64.7,
            "heatindex_c": 18.1,
            "heatindex_f": 64.7,
            "dewpoint_c": 13.9,
            "dewpoint_f": 57.1,
            "will_it_rain": 1,
            "chance_of_rain": 77,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.6,
            "gust_kph": 20.3,
            "uv": 4
          },
          {
            "time_epoch": 1695718800,
            "time": "2023-09-26 10:00",
            "temp_c": 18.9,
            "temp_f": 66,
            "is_day": 1,
            "condition": {
              "text": "Thundery outbreaks possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/200.png",
              "code": 1087
            },
            "wind_mph": 10.3,
            "wind_kph": 16.6,
            "wind_degree": 216,
            "wind_dir": "SW",
            "pressure_mb": 1015,
            "pressure_in": 29.98,
            "precip_mm": 0.04,
            "precip_in": 0,
            "humidity": 70,
            "cloud": 85,
            "feelslike_c": 18.9,
            "feelslike_f": 66,
            "windchill_c": 18.9,
            "windchill_f": 66,
            "heatindex_c": 18.9,
            "heatindex_f": 66,
            "dewpoint_c": 13.2,
            "dewpoint_f": 55.8,
            "will_it_rain": 0,
            "chance_of_rain": 70,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9,
            "vis_miles": 5,
            "gust_mph": 13.3,
            "gust_kph": 21.4,
            "uv": 4
          },
          {
            "time_epoch": 1695722400,
            "time": "2023-09-26 11:00",
            "temp_c": 20.1,
            "temp_f": 68.1,
            "is_day": 1,
            "condition": {
              "text": "Light rain shower",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
              "code": 1240
            },
            "wind_mph": 11.9,
            "wind_kph": 19.1,
            "wind_degree": 220,
            "wind_dir": "SW",
            "pressure_mb": 1015,
            "pressure_in": 29.98,
            "precip_mm": 0.22,
            "precip_in": 0.01,
            "humidity": 66,
            "cloud": 100,
            "feelslike_c": 20.1,
            "feelslike_f": 68.1,
            "windchill_c": 20.1,
            "windchill_f": 68.1,
            "heatindex_c": 20.1,
            "heatindex_f": 68.1,
            "dewpoint_c": 13.6,
            "dewpoint_f": 56.5,
            "will_it_rain": 0,
            "chance_of_rain": 61,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 14.2,
            "gust_kph": 22.9,
            "uv": 5
          },
          {
            "time_epoch": 1695726000,
            "time": "2023-09-26 12:00",
            "temp_c": 18.8,
            "temp_f": 65.9,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 10.3,
            "wind_kph": 16.6,
            "wind_degree": 221,
            "wind_dir": "SW",
            "pressure_mb": 1015,
            "pressure_in": 29.98,
            "precip_mm": 0.03,
            "precip_in": 0,
            "humidity": 74,
            "cloud": 53,
            "feelslike_c": 18.8,
            "feelslike_f": 65.9,
            "windchill_c": 18.8,
            "windchill_f": 65.9,
            "heatindex_c": 18.8,
            "heatindex_f": 65.9,
            "dewpoint_c": 14.1,
            "dewpoint_f": 57.3,
            "will_it_rain": 1,
            "chance_of_rain": 87,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.1,
            "gust_kph": 21.1,
            "uv": 4
          },
          {
            "time_epoch": 1695729600,
            "time": "2023-09-26 13:00",
            "temp_c": 20.5,
            "temp_f": 68.9,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 10.7,
            "wind_kph": 17.3,
            "wind_degree": 221,
            "wind_dir": "SW",
            "pressure_mb": 1015,
            "pressure_in": 29.97,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 60,
            "cloud": 35,
            "feelslike_c": 20.5,
            "feelslike_f": 68.9,
            "windchill_c": 20.5,
            "windchill_f": 68.9,
            "heatindex_c": 20.5,
            "heatindex_f": 68.9,
            "dewpoint_c": 12.4,
            "dewpoint_f": 54.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.3,
            "gust_kph": 19.9,
            "uv": 6
          },
          {
            "time_epoch": 1695733200,
            "time": "2023-09-26 14:00",
            "temp_c": 21.6,
            "temp_f": 70.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 10.7,
            "wind_kph": 17.3,
            "wind_degree": 214,
            "wind_dir": "SW",
            "pressure_mb": 1014,
            "pressure_in": 29.95,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 48,
            "cloud": 21,
            "feelslike_c": 21.6,
            "feelslike_f": 71,
            "windchill_c": 21.6,
            "windchill_f": 71,
            "heatindex_c": 24.3,
            "heatindex_f": 75.7,
            "dewpoint_c": 10.2,
            "dewpoint_f": 50.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.3,
            "gust_kph": 19.9,
            "uv": 6
          },
          {
            "time_epoch": 1695736800,
            "time": "2023-09-26 15:00",
            "temp_c": 21.5,
            "temp_f": 70.7,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 12.5,
            "wind_kph": 20.2,
            "wind_degree": 216,
            "wind_dir": "SW",
            "pressure_mb": 1014,
            "pressure_in": 29.95,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 48,
            "cloud": 24,
            "feelslike_c": 21.5,
            "feelslike_f": 70.7,
            "windchill_c": 21.5,
            "windchill_f": 70.7,
            "heatindex_c": 24.3,
            "heatindex_f": 75.7,
            "dewpoint_c": 10.2,
            "dewpoint_f": 50.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 14.9,
            "gust_kph": 24,
            "uv": 6
          },
          {
            "time_epoch": 1695740400,
            "time": "2023-09-26 16:00",
            "temp_c": 20.6,
            "temp_f": 69.1,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 11.2,
            "wind_kph": 18,
            "wind_degree": 218,
            "wind_dir": "SW",
            "pressure_mb": 1014,
            "pressure_in": 29.95,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 56,
            "cloud": 37,
            "feelslike_c": 20.6,
            "feelslike_f": 69.1,
            "windchill_c": 20.6,
            "windchill_f": 69.1,
            "heatindex_c": 20.6,
            "heatindex_f": 69.1,
            "dewpoint_c": 11.5,
            "dewpoint_f": 52.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 14,
            "gust_kph": 22.5,
            "uv": 6
          },
          {
            "time_epoch": 1695744000,
            "time": "2023-09-26 17:00",
            "temp_c": 19.2,
            "temp_f": 66.6,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 11.4,
            "wind_kph": 18.4,
            "wind_degree": 220,
            "wind_dir": "SW",
            "pressure_mb": 1015,
            "pressure_in": 29.97,
            "precip_mm": 0.02,
            "precip_in": 0,
            "humidity": 66,
            "cloud": 62,
            "feelslike_c": 19.2,
            "feelslike_f": 66.6,
            "windchill_c": 19.2,
            "windchill_f": 66.6,
            "heatindex_c": 19.2,
            "heatindex_f": 66.6,
            "dewpoint_c": 12.7,
            "dewpoint_f": 54.9,
            "will_it_rain": 0,
            "chance_of_rain": 60,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 15.2,
            "gust_kph": 24.5,
            "uv": 4
          },
          {
            "time_epoch": 1695747600,
            "time": "2023-09-26 18:00",
            "temp_c": 18.1,
            "temp_f": 64.6,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 9.8,
            "wind_kph": 15.8,
            "wind_degree": 218,
            "wind_dir": "SW",
            "pressure_mb": 1016,
            "pressure_in": 29.99,
            "precip_mm": 0.02,
            "precip_in": 0,
            "humidity": 74,
            "cloud": 72,
            "feelslike_c": 18.1,
            "feelslike_f": 64.6,
            "windchill_c": 18.1,
            "windchill_f": 64.6,
            "heatindex_c": 18.1,
            "heatindex_f": 64.6,
            "dewpoint_c": 13.5,
            "dewpoint_f": 56.2,
            "will_it_rain": 1,
            "chance_of_rain": 82,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.4,
            "gust_kph": 21.6,
            "uv": 4
          },
          {
            "time_epoch": 1695751200,
            "time": "2023-09-26 19:00",
            "temp_c": 17.4,
            "temp_f": 63.3,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 10.1,
            "wind_kph": 16.2,
            "wind_degree": 221,
            "wind_dir": "SW",
            "pressure_mb": 1016,
            "pressure_in": 30.01,
            "precip_mm": 0.03,
            "precip_in": 0,
            "humidity": 79,
            "cloud": 71,
            "feelslike_c": 17.4,
            "feelslike_f": 63.3,
            "windchill_c": 17.4,
            "windchill_f": 63.3,
            "heatindex_c": 17.4,
            "heatindex_f": 63.3,
            "dewpoint_c": 13.8,
            "dewpoint_f": 56.8,
            "will_it_rain": 1,
            "chance_of_rain": 77,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.9,
            "gust_kph": 22.4,
            "uv": 1
          },
          {
            "time_epoch": 1695754800,
            "time": "2023-09-26 20:00",
            "temp_c": 16.9,
            "temp_f": 62.5,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 7.8,
            "wind_kph": 12.6,
            "wind_degree": 225,
            "wind_dir": "SW",
            "pressure_mb": 1016,
            "pressure_in": 30.01,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 81,
            "cloud": 52,
            "feelslike_c": 16.9,
            "feelslike_f": 62.5,
            "windchill_c": 16.9,
            "windchill_f": 62.5,
            "heatindex_c": 16.9,
            "heatindex_f": 62.5,
            "dewpoint_c": 13.6,
            "dewpoint_f": 56.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.8,
            "gust_kph": 17.5,
            "uv": 1
          },
          {
            "time_epoch": 1695758400,
            "time": "2023-09-26 21:00",
            "temp_c": 16.2,
            "temp_f": 61.2,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 6.9,
            "wind_kph": 11.2,
            "wind_degree": 239,
            "wind_dir": "WSW",
            "pressure_mb": 1017,
            "pressure_in": 30.03,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 83,
            "cloud": 42,
            "feelslike_c": 16.2,
            "feelslike_f": 61.2,
            "windchill_c": 16.2,
            "windchill_f": 61.2,
            "heatindex_c": 16.2,
            "heatindex_f": 61.2,
            "dewpoint_c": 13.4,
            "dewpoint_f": 56.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10,
            "gust_kph": 16,
            "uv": 1
          },
          {
            "time_epoch": 1695762000,
            "time": "2023-09-26 22:00",
            "temp_c": 15.7,
            "temp_f": 60.2,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4.9,
            "wind_kph": 7.9,
            "wind_degree": 236,
            "wind_dir": "WSW",
            "pressure_mb": 1017,
            "pressure_in": 30.03,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 85,
            "cloud": 19,
            "feelslike_c": 15.7,
            "feelslike_f": 60.2,
            "windchill_c": 15.7,
            "windchill_f": 60.2,
            "heatindex_c": 15.7,
            "heatindex_f": 60.2,
            "dewpoint_c": 13.2,
            "dewpoint_f": 55.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.1,
            "gust_kph": 11.5,
            "uv": 1
          },
          {
            "time_epoch": 1695765600,
            "time": "2023-09-26 23:00",
            "temp_c": 15.2,
            "temp_f": 59.4,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4.3,
            "wind_kph": 6.8,
            "wind_degree": 241,
            "wind_dir": "WSW",
            "pressure_mb": 1017,
            "pressure_in": 30.04,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 86,
            "cloud": 22,
            "feelslike_c": 15.2,
            "feelslike_f": 59.4,
            "windchill_c": 15.2,
            "windchill_f": 59.4,
            "heatindex_c": 15.2,
            "heatindex_f": 59.4,
            "dewpoint_c": 13,
            "dewpoint_f": 55.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.2,
            "gust_kph": 10,
            "uv": 1
          }
        ]
      }
    ]
  }
}
